# Generated by Django 4.2.1 on 2023-05-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_rename_project_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='tag',
        ),
    ]
