# Generated by Django 4.2.1 on 2023-05-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_rename_name_tags_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
