# Generated by Django 4.2.1 on 2023-05-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_rename_tags_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='nombre',
        ),
    ]
