# Generated by Django 4.2.1 on 2023-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_rename_tag_tag_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nombre',
            new_name='symbol',
        ),
        migrations.AddField(
            model_name='tag',
            name='debt_equ',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='f_eps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='f_pe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='insiders',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='my_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='my_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='profit_m',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='roa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='roe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='short_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='t_eps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='t_pe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='t_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='upside',
            field=models.FloatField(default=0),
        ),
    ]
