# Generated by Django 4.2.1 on 2023-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0008_alter_tag_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("associated_tags", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
