# Generated by Django 4.2.1 on 2023-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0009_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="associated_tags",
            field=models.CharField(default="[]", max_length=5000),
        ),
    ]
