# Generated by Django 4.2.1 on 2023-07-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0010_alter_category_associated_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
